# Site settings
title: Blog
description: Blog Adrián García

# User settings
username: Adriá Developer
user_description:
user_title: Developer Web
email: adrianalh93@gmail.com
twitter_username:
github_username:  adrian93
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
